### ISSUE TITLE
Failure localization - Login Page

### ISSUE THREAD

**Issue by etms51** [ZZJHONS/ZravianX#1]
Description: When i enter the my nickname and a wrong password to login into my account. IF i choose put a wrong password, the System said which the password is wrong.  In this error message, the game show three strings don't localized. (Screenshot 1)

PW_FORGOTTEN 
PW_REQUEST 
PW_GENERATE

Step by Step:

1)I write in my favorite browser  this following link: http://deepspace.site40.net/login.php
2)I put my nickname and a wrong password.
3)the game system inform me which the password is wrong
4)Under the fields Nickname and Password, there are three strings don't  localized. (Screenshot 1) 

Browser: Google Chrome v.16.0.912.63 (ed anche gli altri browser in utilizzo).
Screenshot: 
image 1 => http://dl.dropbox.com/u/34043118/Travian_4/three_Strings_dont_Localized_Login.jpg

please fix it

**Comment by ZZJHONS** [comment]
This is easy, only need add to en.php: define("PW_FORGOTTEN", "Forgot your pasword?"); and other, Soon i upload it

**Comment by ghost** [comment]
I fixed it, please check Issue #5
